package com.bill.dao;

import com.bill.model.EnjoyUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

//@Mapper
public interface EnjoyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enjoy_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enjoy_user
     *
     * @mbggenerated
     */
    int insert(EnjoyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enjoy_user
     *
     * @mbggenerated
     */
    EnjoyUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enjoy_user
     *
     * @mbggenerated
     */
    List<EnjoyUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enjoy_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnjoyUser record);

    EnjoyUser findByUsernameAndPasswd(@Param("username") String username, @Param("passwd") String passwd);
}